/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Talleres;

import Clases.Ciudad;
import Clases.Cliente;
import Clases.Comuna;
import Clases.Direccion;
import Clases.Taller;
import Operaciones.LlenarCombo;
import Operaciones.OperacionesTaller;
import Validacion.Validar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigo
 */
public class ModificarTaller extends javax.swing.JPanel {

    //Instanciamos las clases correspondientes para trabajar
    OperacionesTaller op = new OperacionesTaller();
    LlenarCombo llenarCombo = new LlenarCombo();

    /**
     * Creates new form ModificarTaller
     */
    public ModificarTaller() throws SQLException {
        initComponents();
        Validar.validarCaracter(jtfNombre, 20);
        Validar.validarCaracter(jtfCalle, 20);
        Validar.validarCorreo(jtfCorreo, jlMsgEmail);
        Validar.validarNumero(jtfTelefono, 9);
        Validar.validarNumero(jtfNumeroCalle, 6);
        llenarCombo.llenarComboCiudad(jcbCiudad);
        llenarCombo.llenarComboComuna(jcbComuna, 0);

    }

    public void habilitarBotonBuscar() {

        String nombreTaller = jtfNombre.getText();

        if (nombreTaller.isEmpty()) {
            jbBuscar.setEnabled(false);
        } else {
            jbBuscar.setEnabled(true);
        }

    }

    public void limpiarModificar() {
        jtfNombre.setEditable(true);
        jtfCorreo.setEnabled(false);
        jtfCalle.setEnabled(false);
        jtfNumeroCalle.setEnabled(false);
        jtfTelefono.setEnabled(false);
        jcbCiudad.setEnabled(false);
        jcbComuna.setEnabled(false);
        jtfNombre.setText("");
        jtfCorreo.setText("");
        jtfCalle.setText("");
        jtfNumeroCalle.setText("");
        jtfTelefono.setText("");
        jlMsgEmail.setText("");
        jcbCiudad.setSelectedIndex(0);
        jcbComuna.setSelectedIndex(0);

    }

    public void habilitarCampos() {
        jtfNombre.setEditable(false);
        jtfCorreo.setEnabled(true);
        jtfCalle.setEnabled(true);
        jtfNumeroCalle.setEnabled(true);
        jtfTelefono.setEnabled(true);
        jcbCiudad.setEnabled(true);
        jcbComuna.setEnabled(true);

    }
    
     public void habilitarBotonModificar() {
         
        boolean correo = Validar.validarCorreo(jtfCorreo, jlMsgEmail);
        String nombre = jtfNombre.getText();
        String calle = jtfCalle.getText();
        String numeroCalle = jtfNumeroCalle.getText();
        int telefono = jtfTelefono.getText().length();

        if ((telefono != 9) || calle.isEmpty() || numeroCalle.isEmpty() || nombre.isEmpty() || correo || jcbCiudad.getSelectedIndex() == 0 || jcbComuna.getSelectedIndex() == 0) {
            jbModificar.setEnabled(false);
        } else {
            jbModificar.setEnabled(true);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jtfCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcbCiudad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jbModificar = new javax.swing.JButton();
        jtfCalle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfNumeroCalle = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcbComuna = new javax.swing.JComboBox<>();
        jbBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlMsgEmail = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 0));
        kGradientPanel1.setkGradientFocus(800);
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 0, 0));

        jtfCorreo.setEnabled(false);
        jtfCorreo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfCorreoCaretUpdate(evt);
            }
        });
        jtfCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCorreoActionPerformed(evt);
            }
        });

        jLabel4.setText("Ciudad");

        jLabel9.setText("Email");

        jcbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCiudad.setEnabled(false);
        jcbCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCiudadItemStateChanged(evt);
            }
        });

        jLabel6.setText("Telefono");

        jbModificar.setText("Modificar");
        jbModificar.setEnabled(false);
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jtfCalle.setEnabled(false);
        jtfCalle.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfCalleCaretUpdate(evt);
            }
        });
        jtfCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCalleActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre");

        jtfNumeroCalle.setEnabled(false);
        jtfNumeroCalle.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfNumeroCalleCaretUpdate(evt);
            }
        });
        jtfNumeroCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeroCalleActionPerformed(evt);
            }
        });

        jLabel10.setText("Calle");

        jcbComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbComuna.setEnabled(false);
        jcbComuna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbComunaItemStateChanged(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.setEnabled(false);
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Modificar Taller");

        jLabel5.setText("Comuna");

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unnamed.png"))); // NOI18N

        jLabel8.setText("Numero");

        jlMsgEmail.setForeground(new java.awt.Color(0, 0, 0));

        jtfNombre.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfNombreCaretUpdate(evt);
            }
        });
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jtfTelefono.setEnabled(false);
        jtfTelefono.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfTelefonoCaretUpdate(evt);
            }
        });
        jtfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNombre)
                            .addComponent(jtfTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jlMsgEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jbBuscar))
                                .addGap(18, 18, 18)
                                .addComponent(jbModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jbCancelar))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(16, 16, 16)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfCalle)
                            .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jcbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(37, 37, 37)
                                .addComponent(jtfNumeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3)))
                .addGap(126, 126, 126))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(63, 63, 63)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbModificar)
                    .addComponent(jbBuscar)
                    .addComponent(jbCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlMsgEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jtfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfNumeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
       
         int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas modificarlo? ");

        if (opcion == 0) {
            Taller taller = new Taller();
            Direccion dire = new Direccion();
          
            boolean estado;

            taller.setNombreSucursal(jtfNombre.getText());
            taller.setEmail(jtfCorreo.getText());
            taller.setTelefono(jtfTelefono.getText());

            dire.setNombreCalle(jtfCalle.getText());
            dire.setNumeroCalle(jtfNumeroCalle.getText());
            Comuna comuna = (Comuna) jcbComuna.getSelectedItem();
            int idCom = comuna.getIdComuna();
            dire.setIdComuna(String.valueOf(idCom));

            estado = op.modificarTaller(taller, dire);

            if (estado) {
                JOptionPane.showMessageDialog(null, "Taller modificado correctamente");
                limpiarModificar();
            } else {
                JOptionPane.showMessageDialog(null, "Ups Algo Salio mal y no se pudo modificar el Talller");
            }
        }else if(opcion==2){
            
            limpiarModificar();
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jcbCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCiudadItemStateChanged
        habilitarBotonModificar();
        Ciudad ciudad = (Ciudad) this.jcbCiudad.getSelectedItem();//recuperamos el objeto (Ciudad) que esta en jComboBox, segun el Item Seleccionda
        int idCiu = ciudad.getIdCiudad();//Recuperamos el Id del Objeto Ciudad 
        try {
            llenarCombo.llenarComboComuna(jcbComuna, idCiu);//enviamos el JComboBoxComuna y el Id de la de la Ciudad 
        } catch (SQLException ex) {
            Logger.getLogger(ModificarTaller.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbCiudadItemStateChanged

    private void jtfCalleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfCalleCaretUpdate
        habilitarBotonBuscar();
    }//GEN-LAST:event_jtfCalleCaretUpdate

    private void jtfCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCalleActionPerformed

    private void jtfNumeroCalleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfNumeroCalleCaretUpdate
        habilitarBotonBuscar();
    }//GEN-LAST:event_jtfNumeroCalleCaretUpdate

    private void jtfNumeroCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeroCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroCalleActionPerformed

    private void jcbComunaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbComunaItemStateChanged
        habilitarBotonModificar();
    }//GEN-LAST:event_jcbComunaItemStateChanged

    private void jtfNombreCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfNombreCaretUpdate
        habilitarBotonBuscar();
    }//GEN-LAST:event_jtfNombreCaretUpdate

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfTelefonoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfTelefonoCaretUpdate
        habilitarBotonModificar();
    }//GEN-LAST:event_jtfTelefonoCaretUpdate

    private void jtfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelefonoActionPerformed

    private void jtfCorreoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfCorreoCaretUpdate
        habilitarBotonModificar();
    }//GEN-LAST:event_jtfCorreoCaretUpdate

    private void jtfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCorreoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        String nombre = jtfNombre.getText();
        Taller taller = new Taller();
        taller = op.obtenerTaller(nombre);

        if (taller == null) {
            JOptionPane.showMessageDialog(null, "Nombre de Sucursal no se encuentra en la BD");
        } else {

            jtfNombre.setText(taller.getNombreSucursal());
            jtfCorreo.setText(taller.getEmail());
            jtfCalle.setText(taller.getNombreCalle());
            jtfNumeroCalle.setText(taller.getNumeroCalle());
            jtfTelefono.setText(taller.getTelefono());
           
            Ciudad ciudadAux = new Ciudad();
            ciudadAux.setIdCiudad(taller.getIdCiudad());
            ComboBoxModel mod = jcbCiudad.getModel();
            for (int i = 0; i < mod.getSize(); i++) {
                Ciudad ciu = (Ciudad) mod.getElementAt(i);
                if (ciu.getIdCiudad() == ciudadAux.getIdCiudad()) {
                    jcbCiudad.setSelectedItem(ciu);
                }
            }

            Comuna comunaAux = new Comuna();
            comunaAux.setIdComuna(taller.getIdComuna());
            ComboBoxModel modCom = jcbComuna.getModel();
            for (int i = 0; i < modCom.getSize(); i++) {
                Comuna com = (Comuna) modCom.getElementAt(i);
                if (com.getIdComuna() == comunaAux.getIdComuna()) {
                    jcbComuna.setSelectedItem(com);
                }
            }

            habilitarCampos();
            jbModificar.setEnabled(true);

        }

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
       limpiarModificar();
    }//GEN-LAST:event_jbCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox<String> jcbCiudad;
    private javax.swing.JComboBox<String> jcbComuna;
    private javax.swing.JLabel jlMsgEmail;
    private javax.swing.JTextField jtfCalle;
    private javax.swing.JTextField jtfCorreo;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNumeroCalle;
    private javax.swing.JTextField jtfTelefono;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
