package Vista.Talleres;

import Clases.Ciudad;
import Clases.Comuna;
import Clases.Direccion;
import Clases.Taller;
import Operaciones.LlenarCombo;
import Operaciones.OperacionesTaller;
import Validacion.Validar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author felipeOrellana
 */
public class RegistrarTaller extends javax.swing.JPanel {

    OperacionesTaller op = new OperacionesTaller();
    LlenarCombo llenarCombo = new LlenarCombo();

    public RegistrarTaller() throws SQLException {
        initComponents();
        Validar.validarCaracter(jtfNombre, 15);
        Validar.validarCaracter(jtfCalle, 15);
        Validar.validarNumero(jtfNumeroCalle, 5);
        Validar.validarNumero(jtfTelefono, 9);
        llenarCombo.llenarComboCiudad(jcbCiudad);
        llenarCombo.llenarComboComuna(jcbComuna, 0);
    }

    /**
     * Metodo que permite habilita el boton registrar siempre y cuando los
     * campos contengan informacion y que los JCombo esten con una pcion valida
     */
    public void habilitarBotonRegistrar() {

        boolean correo = Validar.validarCorreo(jtfCorreo, jlMsgEmail);

        String nombre = jtfNombre.getText();
        String calle = jtfCalle.getText();
        String numeroCalle = jtfNumeroCalle.getText();
        int largoTelefono = jtfTelefono.getText().length();

        if ((largoTelefono != 9) || nombre.isEmpty() || calle.isEmpty() || numeroCalle.isEmpty() || !correo || jcbCiudad.getSelectedIndex() == 0 || jcbComuna.getSelectedIndex() == 0) {
            jButtonRegistrar.setEnabled(false);
        } else {
            jButtonRegistrar.setEnabled(true);
        }

    }

    /**
     * Metodo que permite limpiar los campos despues de una accion
     */
    public void limpiarRegistrarTaller() {

        jtfNombre.setText("");
        jtfCalle.setText("");
        jtfCorreo.setText("");
        jtfTelefono.setText("");
        jtfNumeroCalle.setText("");
        jcbCiudad.setSelectedIndex(0);
        jcbComuna.setSelectedIndex(0);
        jlMsgEmail.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jtfCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbCiudad = new javax.swing.JComboBox<>();
        jtfCalle = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();
        jtfNumeroCalle = new javax.swing.JTextField();
        jcbComuna = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlMsgEmail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setVerifyInputWhenFocusTarget(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 0));
        kGradientPanel1.setkGradientFocus(800);
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Taller");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unnamed.png"))); // NOI18N

        jtfNombre.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfNombreCaretUpdate(evt);
            }
        });

        jtfTelefono.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfTelefonoCaretUpdate(evt);
            }
        });

        jtfCorreo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfCorreoCaretUpdate(evt);
            }
        });

        jLabel9.setText("Email");

        jLabel6.setText("Telefono");

        jLabel3.setText("Nombre Sucursal");

        jLabel7.setText("Calle");

        jLabel4.setText("Ciudad");

        jcbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCiudadItemStateChanged(evt);
            }
        });

        jtfCalle.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfCalleCaretUpdate(evt);
            }
        });

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setEnabled(false);
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jtfNumeroCalle.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfNumeroCalleCaretUpdate(evt);
            }
        });
        jtfNumeroCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeroCalleActionPerformed(evt);
            }
        });

        jcbComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbComuna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbComunaItemStateChanged(evt);
            }
        });

        jLabel5.setText("Comuna");

        jLabel8.setText("Numero");

        jlMsgEmail.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRegistrar)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfNombre)
                                    .addComponent(jtfTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(jlMsgEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(66, 66, 66)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jcbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(37, 37, 37)
                                        .addComponent(jtfNumeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel1))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlMsgEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addComponent(jButtonRegistrar))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfNumeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNumeroCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeroCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroCalleActionPerformed

    private void jtfNombreCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfNombreCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jtfNombreCaretUpdate

    private void jtfTelefonoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfTelefonoCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jtfTelefonoCaretUpdate

    private void jtfCorreoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfCorreoCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jtfCorreoCaretUpdate

    private void jtfCalleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfCalleCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jtfCalleCaretUpdate

    private void jtfNumeroCalleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfNumeroCalleCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jtfNumeroCalleCaretUpdate

    private void jcbCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCiudadItemStateChanged
        habilitarBotonRegistrar();
        Ciudad ciudad = (Ciudad) this.jcbCiudad.getSelectedItem();//recuperamos el objeto (Ciudad) que esta en jComboBox, segun el Item Seleccionda
        int idCiu = ciudad.getIdCiudad();//Recuperamos el Id del Objeto Ciudad 
        try {
            llenarCombo.llenarComboComuna(jcbComuna, idCiu);//enviamos el JComboBoxComuna y el Id de la de la Ciudad 
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarTaller.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbCiudadItemStateChanged

    private void jcbComunaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbComunaItemStateChanged
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jcbComunaItemStateChanged

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        Taller taller = new Taller();
        Direccion dire = new Direccion();

        boolean estado;

        //Recuperamos los datos y los asignamos a los Objetos Taller y Direccion
        taller.setNombreSucursal(jtfNombre.getText());
        taller.setEmail(jtfCorreo.getText());
        taller.setTelefono(jtfTelefono.getText());

        dire.setNombreCalle(jtfCalle.getText());
        dire.setNumeroCalle(jtfNumeroCalle.getText());
        Comuna comuna = (Comuna) jcbComuna.getSelectedItem();
        int idCom = comuna.getIdComuna();
        dire.setIdComuna(String.valueOf(idCom));

        estado = op.ingresarTaller(taller, dire);

        if (estado) {
            JOptionPane.showMessageDialog(null, "Taller ingresado correctamente");
            limpiarRegistrarTaller();
        } else {
            JOptionPane.showMessageDialog(null, "Ups Algo Salio mal y no se pudo registrar el Taller");
        }


    }//GEN-LAST:event_jButtonRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcbCiudad;
    private javax.swing.JComboBox<String> jcbComuna;
    private javax.swing.JLabel jlMsgEmail;
    private javax.swing.JTextField jtfCalle;
    private javax.swing.JTextField jtfCorreo;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNumeroCalle;
    private javax.swing.JTextField jtfTelefono;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
