/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Automovil;

import Clases.Automovil;
import Clases.Color;
import Clases.Marca;
import Clases.Modelo;
import Operaciones.LlenarCombo;
import Operaciones.OperacionesAuto;
import Validacion.Validar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigo
 */
public class ModificarAuto extends javax.swing.JPanel {

    LlenarCombo llenarCombo = new LlenarCombo();
    OperacionesAuto op = new OperacionesAuto();

    /**
     * Creates new form ModificarAuto
     *
     * @throws java.sql.SQLException
     */
    public ModificarAuto() throws SQLException {
        initComponents();
        Validar.validarCaracter(jtfPatenteLetra, 4);
        Validar.validarNumero(jtfPatenteNumero, 2);
        Validar.validarNumero(jTextFieldKilometraje, 9);
        Validar.validarNumero(jTextFieldNumMotor, 9);
        llenarCombo.llenarComboColor(jcColor);
        llenarCombo.llenarComboMarca(jcMarca);
        llenarCombo.llenarComboModelo(jcModelo, 0);
    }

    public void habilitarCampos() {
        jTextRut.setEnabled(true);
        jTextRut.setEditable(false);
        jTextFieldKilometraje.setEnabled(true);
        jTextFieldNumMotor.setEnabled(true);
        jtfPatenteLetra.setEditable(false);
        jtfPatenteNumero.setEditable(false);
        jcAno.setEnabled(true);
        jcColor.setEnabled(true);
        jcMarca.setEnabled(true);
        jcModelo.setEnabled(true);
    }

    public void limpiarModificarAuto() {
        jTextRut.setEnabled(false);
        jTextFieldKilometraje.setEnabled(false);
        jTextFieldNumMotor.setEnabled(false);
        jtfPatenteLetra.setEditable(true);
        jtfPatenteNumero.setEditable(true);
        jTextRut.setText("");
        jTextFieldKilometraje.setText("");
        jTextFieldNumMotor.setText("");
        jtfPatenteLetra.setText("");
        jtfPatenteNumero.setText("");
        jcAno.setEnabled(false);
        jcAno.setSelectedIndex(0);
        jcColor.setEnabled(false);
        jcColor.setSelectedIndex(0);
        jcMarca.setEnabled(false);
        jcMarca.setSelectedIndex(0);
        jcModelo.setEnabled(false);
        jcModelo.setSelectedIndex(0);
        jButtonModificar.setEnabled(false);
        jbBuscar.setEnabled(false);
    }

    public void habilitarBotonModificar() {

        String kilometraje = jTextFieldKilometraje.getText();
        String numMotor = jTextFieldNumMotor.getText();

        if (kilometraje.isEmpty() || numMotor.isEmpty() || jcAno.getSelectedIndex() == 0 || jcColor.getSelectedIndex() == 0 || jcModelo.getSelectedIndex() == 0 || jcMarca.getSelectedIndex() == 0) {
            jButtonModificar.setEnabled(false);
        } else {
            jButtonModificar.setEnabled(true);
        }

    }

    public void habilitarBotonBuscar() {
        int PatenteLetra = jtfPatenteLetra.getText().length();
        int PatenteNumero = jtfPatenteNumero.getText().length();
        if (PatenteLetra != 4 || PatenteNumero != 2) {
            jbBuscar.setEnabled(false);
        } else {
            jbBuscar.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jcMarca = new javax.swing.JComboBox<>();
        jtfPatenteNumero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextRut = new javax.swing.JTextField();
        jcModelo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcColor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtfPatenteLetra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumMotor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKilometraje = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcAno = new javax.swing.JComboBox<>();
        jbBuscar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 0));
        kGradientPanel1.setkGradientFocus(1300);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 51));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unnamed.png"))); // NOI18N

        jcMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Marca", "Audi", "BMW", "Chevrolet", "Kia", "Hyundai", "Jeep" }));
        jcMarca.setEnabled(false);
        jcMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcMarcaItemStateChanged(evt);
            }
        });

        jtfPatenteNumero.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfPatenteNumeroCaretUpdate(evt);
            }
        });

        jLabel9.setText("Rut Dueño");

        jLabel6.setText("Modelo");

        jTextRut.setEnabled(false);
        jTextRut.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextRutCaretUpdate(evt);
            }
        });

        jcModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Modelo", "Modelo 1", "Modelo 2", "Modelo 3" }));
        jcModelo.setEnabled(false);
        jcModelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcModeloItemStateChanged(evt);
            }
        });

        jLabel7.setText("Color");

        jcColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Color", "Color 1", "Color 2", "Color 3" }));
        jcColor.setEnabled(false);
        jcColor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcColorItemStateChanged(evt);
            }
        });

        jLabel3.setText("Nª de Motor");

        jtfPatenteLetra.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfPatenteLetraCaretUpdate(evt);
            }
        });

        jLabel5.setText("Kilometraje");

        jLabel1.setText("Patente");

        jTextFieldNumMotor.setEnabled(false);
        jTextFieldNumMotor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldNumMotorCaretUpdate(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Modificar Automovil");

        jTextFieldKilometraje.setEnabled(false);
        jTextFieldKilometraje.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldKilometrajeCaretUpdate(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.setEnabled(false);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jLabel8.setText("Marca");

        jLabel10.setText("Año");

        jcAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Año", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jcAno.setEnabled(false);
        jcAno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcAnoItemStateChanged(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.setEnabled(false);
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextRut, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(92, 92, 92)
                                    .addComponent(jtfPatenteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(42, 42, 42))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)))
                                    .addGap(18, 18, 18)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNumMotor)
                                        .addComponent(jTextFieldKilometraje)
                                        .addComponent(jcMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcAno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPatenteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(34, 34, 34)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 134, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(128, 128, 128))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfPatenteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPatenteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNumMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jcAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPatenteLetraCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfPatenteLetraCaretUpdate
        habilitarBotonBuscar();
    }//GEN-LAST:event_jtfPatenteLetraCaretUpdate

    private void jtfPatenteNumeroCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfPatenteNumeroCaretUpdate
        habilitarBotonBuscar();
    }//GEN-LAST:event_jtfPatenteNumeroCaretUpdate

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas modificarlo? ");

        if (opcion == 0) {
            Automovil auto = new Automovil();

            boolean estado;

            auto.setRutDueno(jTextRut.getText());
            auto.setKilometraje(jTextFieldKilometraje.getText());
            auto.setnMotor(jTextFieldNumMotor.getText());
            auto.setPatente(jtfPatenteLetra.getText() + jtfPatenteNumero.getText());

            auto.setAno(jcAno.getModel().getSelectedItem().toString());
            
            //Recuperamos el objeto dentro del Jcombo seleccionado y procedemos a sacar su Id(Modelo y Color)
            Modelo modelo = (Modelo) jcModelo.getSelectedItem();
            int idMod = modelo.getIdModelo();
            auto.setIdModelo(String.valueOf(idMod));

            Color color = (Color) jcColor.getSelectedItem();
            int idCol = color.getIdColor();
            auto.setIdColor(String.valueOf(idCol));

            estado = op.modificarAuto(auto);

            if (estado) {
                JOptionPane.showMessageDialog(null, "Auto modificado correctamente");
                limpiarModificarAuto();
            } else {
                JOptionPane.showMessageDialog(null, "Ups Algo Salio mal y no se pudo modificar los datos del Automovil");

            }
        } else if (opcion == 2) {

            limpiarModificarAuto();
        }

    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jcModeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcModeloItemStateChanged
        habilitarBotonModificar();
    }//GEN-LAST:event_jcModeloItemStateChanged

    private void jcColorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcColorItemStateChanged
        habilitarBotonModificar();
    }//GEN-LAST:event_jcColorItemStateChanged

    private void jTextFieldNumMotorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldNumMotorCaretUpdate
        habilitarBotonModificar();
    }//GEN-LAST:event_jTextFieldNumMotorCaretUpdate

    private void jTextFieldKilometrajeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldKilometrajeCaretUpdate
        habilitarBotonModificar();
    }//GEN-LAST:event_jTextFieldKilometrajeCaretUpdate

    private void jcMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcMarcaItemStateChanged
        habilitarBotonModificar();
        Marca marca = (Marca) this.jcMarca.getSelectedItem();

        int idMarca = marca.getIdMarca();
        try {
            llenarCombo.llenarComboModelo(jcModelo, idMarca);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarAuto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcMarcaItemStateChanged

    private void jTextRutCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextRutCaretUpdate

    }//GEN-LAST:event_jTextRutCaretUpdate

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        String patente = jtfPatenteLetra.getText() + jtfPatenteNumero.getText();
        Automovil auto = new Automovil();
        auto = op.obtenerAuto(patente);

        if (auto == null) {
            JOptionPane.showMessageDialog(null, "Auto no se encuentra en la BD");
            limpiarModificarAuto();
        } else {
            jTextRut.setText(auto.getRutDueno());
            jTextFieldNumMotor.setText(auto.getnMotor());
            jTextFieldKilometraje.setText(auto.getKilometraje());
            
            
            String ano = auto.getAno();
            ComboBoxModel modAno = jcAno.getModel();
            for (int i = 0; i < modAno.getSize(); i++) {
                String anoAux = modAno.getElementAt(i).toString();
                if (anoAux.equalsIgnoreCase(ano)) {
                    jcAno.setSelectedItem(anoAux);
                }
            }
            
            //Validamos el id del Objeto recibido con el id que se almacena en el modelo del Jcombo
            Marca marca = new Marca();
            marca.setIdMarca(Integer.parseInt(auto.getIdMarca()));
            ComboBoxModel modMa = jcMarca.getModel();
            for (int i = 0; i < modMa.getSize(); i++) {
                Marca maAux = (Marca) modMa.getElementAt(i);
                if (maAux.getIdMarca() == marca.getIdMarca()) {
                    jcMarca.setSelectedItem(maAux);//le enviamos al modelo el objeto con el id que coincide
                }
            }
            
            //Validamos el id del Objeto recibido con el id que se almacena en el modelo del Jcombo
            Modelo modelo = new Modelo();
            modelo.setIdModelo(Integer.parseInt(auto.getIdModelo()));
            ComboBoxModel modMod = jcModelo.getModel();
            for (int i = 0; i < modMod.getSize(); i++) {
                Modelo moAux = (Modelo) modMod.getElementAt(i);
                if (moAux.getIdModelo() == modelo.getIdModelo()) {
                    jcModelo.setSelectedItem(moAux);//le enviamos al modelo el objeto con el id que coincide
                }
            }
            
            //Validamos el id del Objeto recibido con el id que se almacena en el modelo del Jcombo
            Color color = new Color();
            color.setIdColor(Integer.parseInt(auto.getIdColor()));
            ComboBoxModel modCol = jcColor.getModel();
            for (int i = 0; i < modCol.getSize(); i++) {
                Color coAux = (Color) modCol.getElementAt(i);
                if (coAux.getIdColor() == color.getIdColor()) {
                    jcColor.setSelectedItem(coAux);//le enviamos al modelo el objeto con el id que coincide
                }
            }

            habilitarCampos();
            jButtonModificar.setEnabled(true);
            jbBuscar.setEnabled(false);

        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        limpiarModificarAuto();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jcAnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcAnoItemStateChanged
        habilitarBotonModificar();
    }//GEN-LAST:event_jcAnoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldKilometraje;
    private javax.swing.JTextField jTextFieldNumMotor;
    private javax.swing.JTextField jTextRut;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jcAno;
    private javax.swing.JComboBox<String> jcColor;
    private javax.swing.JComboBox<String> jcMarca;
    private javax.swing.JComboBox<String> jcModelo;
    private javax.swing.JTextField jtfPatenteLetra;
    private javax.swing.JTextField jtfPatenteNumero;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
