/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Automovil;

import Operaciones.OperacionesAuto;
import Operaciones.OperacionesClientes;
import Validacion.Validar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodrigo
 */
public class MostrarAuto extends javax.swing.JPanel {
    
     DefaultTableModel modelo = new DefaultTableModel() {

    };
    private String[] titulo = {"Id", "Patente", "Kilometraje", "Año", "N° Motor", "Marca", "Modelo", "Color", "Rut Dueño"};
    OperacionesAuto op = new OperacionesAuto();
    
    /**
     * Creates new form MostrarAuto
     */
    public MostrarAuto() throws SQLException {
        initComponents();
         modelo = new DefaultTableModel(null, titulo) {
            @Override //Sobreescribiendo el metodo, para no permitir que los campos de la tabla puedan ser editados
            public boolean isCellEditable(int row, int column) {
                if (column == 9) {
                    return true;
                } else {
                    return false;
                }
            }
        };
         Validar.validarCaracter(jtPatenteLetra, 4);
        Validar.validarNumero(jtPatenteNumero, 2);
        jTableAuto.setModel(modelo);
        op.llenarTablaAuto(modelo);
        tamanoTabla();
        
    }

    public void tamanoTabla() {
        if (jTableAuto.getColumnModel().getColumnCount() > 0) {
            jTableAuto.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTableAuto.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTableAuto.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableAuto.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTableAuto.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableAuto.getColumnModel().getColumn(6).setPreferredWidth(130);

        }

    }
    
     public void limpiarTabla() {
        for (int i = 0; i < jTableAuto.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }

    }
    
      public void habilitarBotonBuscar() {
        int PatenteLetra = jtPatenteLetra.getText().length();
        int PatenteNumero = jtPatenteNumero.getText().length();
        if (PatenteLetra != 4 || PatenteNumero != 2) {
            jbBuscar.setEnabled(false);
        } else {
            jbBuscar.setEnabled(true);
        }

    }
      
      public void Actualizar() {

        try {
            limpiarTabla();
            op.llenarTablaAuto(modelo);
            jtPatenteLetra.setText("");
            jtPatenteNumero.setText("");
            tamanoTabla();
        } catch (SQLException ex) {
            Logger.getLogger(MostrarAuto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jbActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAuto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jtPatenteLetra = new javax.swing.JTextField();
        jtPatenteNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setVerifyInputWhenFocusTarget(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 0));
        kGradientPanel1.setkGradientFocus(1300);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 51));
        kGradientPanel1.setkTransparentControls(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Mostrar Automoviles");

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 153));

        jTableAuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAuto);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unnamed.png"))); // NOI18N

        jbBuscar.setText("Buscar");
        jbBuscar.setEnabled(false);
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jtPatenteLetra.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtPatenteLetraCaretUpdate(evt);
            }
        });

        jtPatenteNumero.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtPatenteNumeroCaretUpdate(evt);
            }
        });

        jLabel3.setText("Patente");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbActualizar)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtPatenteLetra))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jbEliminar))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtPatenteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtPatenteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtPatenteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizar)
                    .addComponent(jbBuscar)
                    .addComponent(jbEliminar))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        Actualizar();
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtPatenteLetraCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtPatenteLetraCaretUpdate
        habilitarBotonBuscar();
    }//GEN-LAST:event_jtPatenteLetraCaretUpdate

    private void jtPatenteNumeroCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtPatenteNumeroCaretUpdate
        habilitarBotonBuscar();
    }//GEN-LAST:event_jtPatenteNumeroCaretUpdate

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
       String patenteLetra = jtPatenteLetra.getText();
        String patenteNumero = jtPatenteNumero.getText();
        try {
            modelo = new DefaultTableModel(null, titulo);
            jTableAuto.setModel(modelo);
            op.buscarAuto(modelo,patenteLetra+patenteNumero);
            tamanoTabla();
            if (0==modelo.getRowCount()) {
                JOptionPane.showMessageDialog(null, "Auto no se encuentra en la BD");
                Actualizar();
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(MostrarAuto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        int aux = jTableAuto.getSelectedRow();
        boolean estado;
        if (aux == -1) {

            JOptionPane.showMessageDialog(null, "Seleccione un auto a eliminar");

        } else {

            int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas eliminarlo? ");

            if (opcion == 0) {

                String patente = (String) jTableAuto.getValueAt(aux, 1);
                estado = op.eliminarAuto(patente);
                if (!estado) {
                    JOptionPane.showMessageDialog(null, "Auto no pudo ser  eliminado");
                    Actualizar();
                }else{
                JOptionPane.showMessageDialog(null, "Auto eliminado con exito");
                Actualizar();
                }
            }   
        }
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAuto;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JTextField jtPatenteLetra;
    private javax.swing.JTextField jtPatenteNumero;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
