package Vista;

import Conexion.Conexion;
import Vista.Automovil.*;
import Vista.Clientes.*;
import Vista.Facturas.*;
import Vista.OrdenServicio.*;
import Vista.Presupuesto.*;
import Vista.Talleres.*;
import Vista.Tecnicos.*;
import Vista.TelefonosTaller.*;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 * @author rodrigo
 */
public class PanelPrincipal extends javax.swing.JFrame {

    
    //instancias de todas las interfaces del programa
    RegistrarClientes PanelRegC = new RegistrarClientes();
    RegistrarAutomovil PanelRegA = new RegistrarAutomovil();
    RegistrarTaller PanelRegT = new RegistrarTaller();
    RegistrarMecanico PanelRegM = new RegistrarMecanico();
    RegistrarFactura PanelRegF = new RegistrarFactura();
    RegistrarTelefonoTall PanelRegTelTall = new RegistrarTelefonoTall();
    RegistrarPresupuesto PanelRegP = new RegistrarPresupuesto();
    RegistrarOrdenServicio PanelRegOS = new RegistrarOrdenServicio();
    
    ModificarCliente PanelModC = new ModificarCliente();
    ModificarAuto PanelModA = new ModificarAuto();
    ModificarTaller PanelModT = new ModificarTaller();
    ModificarMecanico PanelModM = new ModificarMecanico();
    ModificarFactura PanelModF = new ModificarFactura();
    ModificarTelefonoTall PanelModTelTall = new ModificarTelefonoTall();
    ModificarPresupuesto PanelModP = new ModificarPresupuesto();
    ModificarOrdenServicio PanelModOS = new ModificarOrdenServicio();
    
    MostrarClientes PanelMosC = new MostrarClientes();
    MostrarAuto PanelMosA = new MostrarAuto();
    MostrarTaller PanelMosT = new MostrarTaller();
    MostrarMecanico PanelMosM = new MostrarMecanico();
    MostrarFacturas PanelMosF = new MostrarFacturas();
    MostrarTelefonosTall PanelMosTelTall = new MostrarTelefonosTall();
    MostrarPresupuesto PanelMosP = new MostrarPresupuesto();
    MostrarOrdenServicio PanelMosOS = new MostrarOrdenServicio();
      
    
    Conexion conector;
    CardLayout vista;

    public PanelPrincipal() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        vista = (CardLayout) JPanelDinamico.getLayout();
        conector = new Conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JPanelDinamico = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        JMenuRegCli = new javax.swing.JMenuItem();
        jMenuModCliente = new javax.swing.JMenuItem();
        jMenuMosCliente = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuRegAuto = new javax.swing.JMenuItem();
        jMenuModAuto = new javax.swing.JMenuItem();
        jMenuMosAuto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuRegTaller = new javax.swing.JMenuItem();
        jMenuModTaller = new javax.swing.JMenuItem();
        jMenuMosTaller = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuRegMecanico = new javax.swing.JMenuItem();
        jMenuModMecanico = new javax.swing.JMenuItem();
        jMenuMosMecanico = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuRegTelTall = new javax.swing.JMenuItem();
        jMenuModTelTall = new javax.swing.JMenuItem();
        jMenuMosTelTall = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuRegFactura = new javax.swing.JMenuItem();
        jMenuModFactura = new javax.swing.JMenuItem();
        jMenuMosFacturas = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuRegPspto = new javax.swing.JMenuItem();
        jMenuModPspto = new javax.swing.JMenuItem();
        jMenuMosPspto = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuRegOS = new javax.swing.JMenuItem();
        jMenuModOS = new javax.swing.JMenuItem();
        jMenuMosOS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/d497d49aef7ded8a336d6ce71d84dff2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPanelDinamico.setBackground(new java.awt.Color(0, 153, 153));
        JPanelDinamico.setLayout(new java.awt.CardLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(94, 181, 198));
        kGradientPanel1.setkStartColor(new java.awt.Color(1, 66, 252));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unnamed.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TALLER MECANICO");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(135, 135, 135))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        JPanelDinamico.add(kGradientPanel1, "card2");

        jMenu1.setText("Clientes");

        jMenu9.setText("Clientes");

        JMenuRegCli.setText("Registrar");
        JMenuRegCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuRegCliActionPerformed(evt);
            }
        });
        jMenu9.add(JMenuRegCli);

        jMenuModCliente.setText("Modificar");
        jMenuModCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModClienteActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuModCliente);

        jMenuMosCliente.setText("Mostrar/Eliminar");
        jMenuMosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMosClienteActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuMosCliente);

        jMenu1.add(jMenu9);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Automovil");

        jMenu10.setText("Automovil");

        jMenuRegAuto.setText("Registrar");
        jMenuRegAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegAutoActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuRegAuto);

        jMenuModAuto.setText("Modificar");
        jMenuModAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModAutoActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuModAuto);

        jMenuMosAuto.setText("Mostrar Autos");
        jMenuMosAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMosAutoActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuMosAuto);

        jMenu5.add(jMenu10);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Talleres");

        jMenu11.setText("Taller");

        jMenuRegTaller.setText("Registrar");
        jMenuRegTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegTallerActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuRegTaller);

        jMenuModTaller.setText("Modificar");
        jMenuModTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModTallerActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuModTaller);

        jMenuMosTaller.setText("Mostrar Todos");
        jMenuMosTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMosTallerActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuMosTaller);

        jMenu3.add(jMenu11);

        jMenu12.setText("Mecanico");

        jMenuRegMecanico.setText("Registrar");
        jMenuRegMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegMecanicoActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuRegMecanico);

        jMenuModMecanico.setText("Modificar");
        jMenuModMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModMecanicoActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuModMecanico);

        jMenuMosMecanico.setText("Mostrar Todos");
        jMenuMosMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMosMecanicoActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuMosMecanico);

        jMenu3.add(jMenu12);

        jMenu14.setText("Contacto");

        jMenu15.setText("Telefonos");

        jMenuRegTelTall.setText("Registrar");
        jMenuRegTelTall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegTelTallActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuRegTelTall);

        jMenuModTelTall.setText("Modificar");
        jMenuModTelTall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModTelTallActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuModTelTall);

        jMenuMosTelTall.setText("Mostrar todos");
        jMenuMosTelTall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMosTelTallActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuMosTelTall);

        jMenu14.add(jMenu15);

        jMenu3.add(jMenu14);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Facturas");

        jMenu2.setText("Factura");

        jMenuRegFactura.setText("Registrar");
        jMenuRegFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegFacturaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuRegFactura);

        jMenuModFactura.setText("Modificar");
        jMenuModFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModFacturaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuModFactura);

        jMenuMosFacturas.setText("Mostrar Facturas");
        jMenuMosFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMosFacturasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuMosFacturas);

        jMenu4.add(jMenu2);

        jMenuBar1.add(jMenu4);

        jMenu13.setText("Presupuesto");

        jMenu16.setText("Presupuesto");

        jMenuRegPspto.setText("Registrar");
        jMenuRegPspto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegPsptoActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuRegPspto);

        jMenuModPspto.setText("Modificar");
        jMenuModPspto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModPsptoActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuModPspto);

        jMenuMosPspto.setText("Mostrar Presupuesto");
        jMenuMosPspto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMosPsptoActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuMosPspto);

        jMenu13.add(jMenu16);

        jMenuBar1.add(jMenu13);

        jMenu6.setText("Orden de Servicio");

        jMenu17.setText("Orden de Servicio");

        jMenuRegOS.setText("Registrar");
        jMenuRegOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegOSActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuRegOS);

        jMenuModOS.setText("Modificar");
        jMenuModOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModOSActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuModOS);

        jMenuMosOS.setText("Mostrar");
        jMenuMosOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMosOSActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuMosOS);

        jMenu6.add(jMenu17);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPanelDinamico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    /**
     * Metodo que se ejecuta con el evento ActionEvent y que llama a la interfaz correspondiente
     * @param evt 
     */
    private void JMenuRegCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuRegCliActionPerformed
        JPanelDinamico.add(PanelRegC, "PanelRegistrarCliente");
        vista.show(JPanelDinamico, "PanelRegistrarCliente");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();

    }//GEN-LAST:event_JMenuRegCliActionPerformed
    
    /**
     * Metodo que se ejecuta con el evento ActionEvent y que llama a la interfaz correspondiente
     * @param evt 
     */
    private void jMenuModClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModClienteActionPerformed
        JPanelDinamico.add(PanelModC, "PanelModificarCliente");
        vista.show(JPanelDinamico, "PanelModificarCliente");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuModClienteActionPerformed

    private void jMenuRegAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegAutoActionPerformed
        try {
            PanelRegA.Actualizar();
        } catch (SQLException ex) {
            Logger.getLogger(PanelPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JPanelDinamico.add(PanelRegA, "PanelRegistrarAuto");
        vista.show(JPanelDinamico, "PanelRegistrarAuto");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuRegAutoActionPerformed

    private void jMenuMosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMosClienteActionPerformed
        PanelMosC.Actualizar();
        JPanelDinamico.add(PanelMosC, "PanelMostrarCliente");
        vista.show(JPanelDinamico, "PanelMostrarCliente");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuMosClienteActionPerformed

    private void jMenuModAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModAutoActionPerformed
        JPanelDinamico.add(PanelModA, "PanelModificarAuto");
        vista.show(JPanelDinamico, "PanelModificarAuto");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuModAutoActionPerformed

    private void jMenuMosAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMosAutoActionPerformed
        PanelMosA.Actualizar();
        JPanelDinamico.add(PanelMosA, "PanelMostrarAuto");
        vista.show(JPanelDinamico, "PanelMostrarAuto");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuMosAutoActionPerformed

    private void jMenuRegTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegTallerActionPerformed
        JPanelDinamico.add(PanelRegT, "PanelRegistrarTaller");
        vista.show(JPanelDinamico, "PanelRegistrarTaller");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuRegTallerActionPerformed

    private void jMenuRegMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegMecanicoActionPerformed
        JPanelDinamico.add(PanelRegM, "PanelRegistrarMecanico");
        vista.show(JPanelDinamico, "PanelRegistrarMecanico");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuRegMecanicoActionPerformed

    private void jMenuModMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModMecanicoActionPerformed
        JPanelDinamico.add(PanelModM, "PanelModificarMecanico");
        vista.show(JPanelDinamico, "PanelModificarMecanico");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuModMecanicoActionPerformed

    private void jMenuMosMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMosMecanicoActionPerformed
        JPanelDinamico.add(PanelMosM, "PanelMostrarMecanico");
        vista.show(JPanelDinamico, "PanelMostrarMecanico");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuMosMecanicoActionPerformed

    private void jMenuModTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModTallerActionPerformed
        JPanelDinamico.add(PanelModT, "PanelModificarTaller");
        vista.show(JPanelDinamico, "PanelModificarTaller");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuModTallerActionPerformed

    private void jMenuMosTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMosTallerActionPerformed
        PanelMosT.Actualizar();
        JPanelDinamico.add(PanelMosT, "PanelMostrarTaller");
        vista.show(JPanelDinamico, "PanelMostrarTaller");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuMosTallerActionPerformed

    private void jMenuRegFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegFacturaActionPerformed
        JPanelDinamico.add(PanelRegF, "PanelRegistrarFactura");
        vista.show(JPanelDinamico, "PanelRegistrarFactura");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuRegFacturaActionPerformed

    private void jMenuModFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModFacturaActionPerformed
        JPanelDinamico.add(PanelModF, "PanelModificarFactura");
        vista.show(JPanelDinamico, "PanelModificarFactura");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuModFacturaActionPerformed

    private void jMenuMosFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMosFacturasActionPerformed
        JPanelDinamico.add(PanelMosF, "PanelMostrarFacturas");
        vista.show(JPanelDinamico, "PanelMostrarFacturas");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuMosFacturasActionPerformed

    private void jMenuMosTelTallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMosTelTallActionPerformed
        JPanelDinamico.add(PanelMosTelTall, "PanelMostrarTelefonoTaller");
        vista.show(JPanelDinamico, "PanelMostrarTelefonoTaller");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuMosTelTallActionPerformed

    private void jMenuModTelTallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModTelTallActionPerformed
        JPanelDinamico.add(PanelModTelTall, "PanelModificarTelefonoTaller");
        vista.show(JPanelDinamico, "PanelModificarTelefonoTaller");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuModTelTallActionPerformed

    private void jMenuRegTelTallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegTelTallActionPerformed
        JPanelDinamico.add(PanelRegTelTall, "PanelRegistrarTelefonoTaller");
        vista.show(JPanelDinamico, "PanelRegistrarTelefonoTaller");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuRegTelTallActionPerformed

    private void jMenuRegPsptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegPsptoActionPerformed
         JPanelDinamico.add(PanelRegP, "PanelRegistrarPresupuesto");
        vista.show(JPanelDinamico, "PanelRegistrarPresupuesto");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuRegPsptoActionPerformed

    private void jMenuModPsptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModPsptoActionPerformed
        JPanelDinamico.add(PanelModP, "PanelModificarPresupuesto");
        vista.show(JPanelDinamico, "PanelModificarPresupuesto");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();  
    }//GEN-LAST:event_jMenuModPsptoActionPerformed

    private void jMenuMosPsptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMosPsptoActionPerformed
        JPanelDinamico.add(PanelMosP, "PanelMostrarPresupuesto");
        vista.show(JPanelDinamico, "PanelMostrarPresupuesto");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuMosPsptoActionPerformed

    private void jMenuRegOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegOSActionPerformed
        JPanelDinamico.add(PanelRegOS, "PanelRegistrarOrdenServicio");
        vista.show(JPanelDinamico, "PanelRegistrarOrdenServicio");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuRegOSActionPerformed

    private void jMenuModOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModOSActionPerformed
        JPanelDinamico.add(PanelModOS, "PanelMostrarOrdenServicio");
        vista.show(JPanelDinamico, "PanelMostrarOrdenServicio");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuModOSActionPerformed

    private void jMenuMosOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMosOSActionPerformed
        JPanelDinamico.add(PanelMosOS, "PanelMostrarOrdenServicio");
        vista.show(JPanelDinamico, "PanelMostrarOrdenServicio");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuMosOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PanelPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PanelPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuRegCli;
    private javax.swing.JPanel JPanelDinamico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuModAuto;
    private javax.swing.JMenuItem jMenuModCliente;
    private javax.swing.JMenuItem jMenuModFactura;
    private javax.swing.JMenuItem jMenuModMecanico;
    private javax.swing.JMenuItem jMenuModOS;
    private javax.swing.JMenuItem jMenuModPspto;
    private javax.swing.JMenuItem jMenuModTaller;
    private javax.swing.JMenuItem jMenuModTelTall;
    private javax.swing.JMenuItem jMenuMosAuto;
    private javax.swing.JMenuItem jMenuMosCliente;
    private javax.swing.JMenuItem jMenuMosFacturas;
    private javax.swing.JMenuItem jMenuMosMecanico;
    private javax.swing.JMenuItem jMenuMosOS;
    private javax.swing.JMenuItem jMenuMosPspto;
    private javax.swing.JMenuItem jMenuMosTaller;
    private javax.swing.JMenuItem jMenuMosTelTall;
    private javax.swing.JMenuItem jMenuRegAuto;
    private javax.swing.JMenuItem jMenuRegFactura;
    private javax.swing.JMenuItem jMenuRegMecanico;
    private javax.swing.JMenuItem jMenuRegOS;
    private javax.swing.JMenuItem jMenuRegPspto;
    private javax.swing.JMenuItem jMenuRegTaller;
    private javax.swing.JMenuItem jMenuRegTelTall;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
