package Vista.Clientes;

import Clases.Ciudad;
import Clases.Cliente;
import Clases.Comuna;
import Clases.Direccion;
import Operaciones.LlenarCombo;
import Operaciones.OperacionesClientes;
import Validacion.Validar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigo
 */
public class ModificarCliente extends javax.swing.JPanel {
     //Instanciamos las clases correspondientes para trabajar
    LlenarCombo llenarCombo = new LlenarCombo();
    OperacionesClientes op = new OperacionesClientes();

    /**
     * Creates new form ModificarCliente
     */
    public ModificarCliente() throws SQLException {
        initComponents();
        Validar.validarRut(jTextRut, jTextFieldDV, jLabelMsjRut);
        Validar.validarNumero(jTextTelefono, 9);
        Validar.validarCaracter(jTextFieldNombres, 20);
        Validar.validarNumero(jtfNumCalle, 6);
        Validar.validarCaracter(jtfCalle, 20);
        llenarCombo.llenarComboCiudad(jcbCiudad);
        llenarCombo.llenarComboComuna(jcbComuna, 0);
    }

    public void habilitarBotonModificar() {

        String nombre = jTextFieldNombres.getText();
        String Paterno = jTextApePaterno.getText();
        String Materno = jTextApeMaterno.getText();
        String Calle = jtfCalle.getText();
        String Numero = jtfNumCalle.getText();
        int telefono = jTextTelefono.getText().length();

        if ((telefono != 9) || Calle.isEmpty() || Numero.isEmpty() || nombre.isEmpty() || Paterno.isEmpty() || Materno.isEmpty() || jcbCiudad.getSelectedIndex() == 0 || jcbComuna.getSelectedIndex() == 0) {
            jButtonModoficar.setEnabled(false);
        } else {
            jButtonModoficar.setEnabled(true);
        }

    }

    public void limpiarModificar() {
        jTextRut.setEditable(true);
        jTextFieldDV.setEditable(true);
        jTextRut.setText("");
        jTextFieldDV.setText("");
        jTextFieldNombres.setText("");
        jTextApePaterno.setText("");
        jTextApeMaterno.setText("");
        jTextTelefono.setText("");
        jtfCalle.setText("");
        jtfNumCalle.setText("");
        jcbCiudad.setSelectedIndex(0);
        jcbComuna.setSelectedIndex(0);
        jLabelMsjRut.setText("");
        jTextFieldNombres.setEnabled(false);
        jTextApePaterno.setEnabled(false);
        jTextApeMaterno.setEnabled(false);
        jTextTelefono.setEnabled(false);
        jtfCalle.setEnabled(false);
        jtfNumCalle.setEnabled(false);
        jcbCiudad.setEnabled(false);
        jcbComuna.setEnabled(false);

    }

    public void habilitarBotonBuscar() {
        boolean estadoJLRut = jLabelMsjRut.isEnabled();
        if (estadoJLRut) {
            jButtonBuscar.setEnabled(false);
        } else {
            jButtonBuscar.setEnabled(true);
        }

    }

    public void habilitarCampos() {
        jTextRut.setEditable(false);
        jTextFieldDV.setEditable(false);
        jTextFieldNombres.setEnabled(true);
        jTextFieldNombres.setEditable(false);
        jTextApePaterno.setEnabled(true);
        jTextApePaterno.setEditable(false);
        jTextApeMaterno.setEnabled(true);
        jTextApeMaterno.setEditable(false);
        jTextTelefono.setEnabled(true);
        jtfCalle.setEnabled(true);
        jtfNumCalle.setEnabled(true);
        jcbCiudad.setEnabled(true);
        jcbComuna.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonModoficar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jtfNumCalle = new javax.swing.JTextField();
        jcbComuna = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelMsjRut = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextRut = new javax.swing.JTextField();
        jTextFieldDV = new javax.swing.JTextField();
        jTextFieldNombres = new javax.swing.JTextField();
        jTextApePaterno = new javax.swing.JTextField();
        jTextApeMaterno = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jtfCalle = new javax.swing.JTextField();
        jcbCiudad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 250, 0));
        kGradientPanel1.setkGradientFocus(800);
        kGradientPanel1.setkStartColor(new java.awt.Color(19, 62, 144));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setEnabled(false);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonModoficar.setText("Modificar");
        jButtonModoficar.setEnabled(false);
        jButtonModoficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoficarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jtfNumCalle.setEnabled(false);
        jtfNumCalle.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfNumCalleCaretUpdate(evt);
            }
        });

        jcbComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbComuna.setEnabled(false);
        jcbComuna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbComunaItemStateChanged(evt);
            }
        });

        jLabel11.setText("N° Calle");

        jLabel9.setText("Comuna:");

        jLabelMsjRut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMsjRut.setForeground(new java.awt.Color(255, 51, 51));
        jLabelMsjRut.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabelMsjRutInputMethodTextChanged(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unnamed.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Modificar Cliente");

        jTextRut.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextRutCaretUpdate(evt);
            }
        });

        jTextFieldDV.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldDVCaretUpdate(evt);
            }
        });

        jTextFieldNombres.setEnabled(false);
        jTextFieldNombres.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldNombresCaretUpdate(evt);
            }
        });

        jTextApePaterno.setEnabled(false);
        jTextApePaterno.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextApePaternoCaretUpdate(evt);
            }
        });

        jTextApeMaterno.setEnabled(false);
        jTextApeMaterno.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextApeMaternoCaretUpdate(evt);
            }
        });

        jTextTelefono.setEnabled(false);
        jTextTelefono.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextTelefonoCaretUpdate(evt);
            }
        });

        jtfCalle.setEnabled(false);
        jtfCalle.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfCalleCaretUpdate(evt);
            }
        });

        jcbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCiudad.setEnabled(false);
        jcbCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCiudadItemStateChanged(evt);
            }
        });

        jLabel8.setText("Ciudad:");

        jLabel10.setText("Calle");

        jLabel7.setText("Telefono:");

        jLabel6.setText("Apellido Materno:");

        jLabel5.setText("Apellido Paterno:");

        jLabel4.setText("Nombres:");

        jLabel1.setText("Rut");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNombres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextApePaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(91, 91, 91)
                        .addComponent(jTextRut, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNumCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelMsjRut, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModoficar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(315, 315, 315))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelMsjRut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonModoficar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar)))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jtfNumCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextRutCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextRutCaretUpdate

        Validar.validarRut(jTextRut, jTextFieldDV, jLabelMsjRut);
        habilitarBotonBuscar();
    }//GEN-LAST:event_jTextRutCaretUpdate

    private void jTextFieldDVCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldDVCaretUpdate

        Validar.validarRut(jTextRut, jTextFieldDV, jLabelMsjRut);
        habilitarBotonBuscar();
    }//GEN-LAST:event_jTextFieldDVCaretUpdate

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String rut = jTextRut.getText();
        String dv = jTextFieldDV.getText();
        Cliente cli = new Cliente();
        cli = op.obtenerCliente(rut, dv);

        if (cli == null) {
            JOptionPane.showMessageDialog(null, "Rut no se encuentra en la BD");
        } else {

            jTextRut.setText("");
            jTextFieldDV.setText("");
            jTextFieldNombres.setText(cli.getNombre());
            jTextApePaterno.setText(cli.getApePaterno());
            jTextApeMaterno.setText(cli.getApeMaterno());
            jTextTelefono.setText(cli.getTelefono());
            System.out.println("dentro de else JButonBuscar antes de rut");
            jTextRut.setText(cli.getRut());
            jTextFieldDV.setText(cli.getDv());
            System.out.println("despues de rut");
            jtfCalle.setText(cli.getNombreCalle());
            jtfNumCalle.setText(cli.getNumeroCalle());
            
            //Validamos el id del Objeto recibido con el id que se almacena en el modelo del Jcombo
            Ciudad ciudadAux = new Ciudad();
            ciudadAux.setIdCiudad(cli.getIdCiudad());
            ComboBoxModel mod = jcbCiudad.getModel();
            for (int i = 0; i < mod.getSize(); i++) {
                Ciudad ciu = (Ciudad) mod.getElementAt(i);
                if (ciu.getIdCiudad() == ciudadAux.getIdCiudad()) {
                    jcbCiudad.setSelectedItem(ciu);//le enviamos al modelo el objeto con el id que coincide
                }
            }
            
            //Validamos el id del Objeto recibido con el id que se almacena en el modelo del Jcombo
            Comuna comunaAux = new Comuna();
            comunaAux.setIdComuna(cli.getIdComuna());
            ComboBoxModel modCom = jcbComuna.getModel();
            for (int i = 0; i < modCom.getSize(); i++) {
                Comuna com = (Comuna) modCom.getElementAt(i);
                if (com.getIdComuna() == comunaAux.getIdComuna()) {
                    jcbComuna.setSelectedItem(com);//le enviamos al modelo el objeto con el id que coincide
                }
            }

            habilitarCampos();
            jButtonModoficar.setEnabled(true);

        }


    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jcbCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCiudadItemStateChanged
        habilitarBotonModificar();
        Ciudad ciudad = (Ciudad) this.jcbCiudad.getSelectedItem();

        int idCiudad = ciudad.getIdCiudad();
        try {
            llenarCombo.llenarComboComuna(jcbComuna, idCiudad);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbCiudadItemStateChanged

    private void jcbComunaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbComunaItemStateChanged
        habilitarBotonModificar();
    }//GEN-LAST:event_jcbComunaItemStateChanged

    private void jTextFieldNombresCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldNombresCaretUpdate
        habilitarBotonModificar();
    }//GEN-LAST:event_jTextFieldNombresCaretUpdate

    private void jtfCalleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfCalleCaretUpdate
        habilitarBotonModificar();
    }//GEN-LAST:event_jtfCalleCaretUpdate

    private void jtfNumCalleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfNumCalleCaretUpdate
        habilitarBotonModificar();
    }//GEN-LAST:event_jtfNumCalleCaretUpdate

    private void jTextApePaternoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextApePaternoCaretUpdate
        habilitarBotonModificar();
    }//GEN-LAST:event_jTextApePaternoCaretUpdate

    private void jTextApeMaternoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextApeMaternoCaretUpdate
        habilitarBotonModificar();
    }//GEN-LAST:event_jTextApeMaternoCaretUpdate

    private void jTextTelefonoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextTelefonoCaretUpdate
        habilitarBotonModificar();
    }//GEN-LAST:event_jTextTelefonoCaretUpdate

    private void jButtonModoficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoficarActionPerformed

        int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas modificarlo? ");

        if (opcion == 0) {
            Cliente cliente = new Cliente();
            Direccion dire = new Direccion();
           //Operaciones op = new Operaciones();
            boolean estado;

            cliente.setRut(jTextRut.getText());
            cliente.setDv(jTextFieldDV.getText());
            cliente.setTelefono(jTextTelefono.getText());

            dire.setNombreCalle(jtfCalle.getText());
            dire.setNumeroCalle(jtfNumCalle.getText());
            Comuna comuna = (Comuna) jcbComuna.getSelectedItem();
            int idCom = comuna.getIdComuna();
            dire.setIdComuna(String.valueOf(idCom));

            estado = op.modificarCliente(cliente, dire);

            if (estado) {
                JOptionPane.showMessageDialog(null, "Cliente modificado correctamente");
                limpiarModificar();
            } else {
                JOptionPane.showMessageDialog(null, "Ups Algo Salio mal y no se pudo modificar el cliente");
            }
        }else if(opcion==2){
            
            limpiarModificar();
        }


    }//GEN-LAST:event_jButtonModoficarActionPerformed

    private void jLabelMsjRutInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabelMsjRutInputMethodTextChanged
        habilitarBotonModificar();
    }//GEN-LAST:event_jLabelMsjRutInputMethodTextChanged

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limpiarModificar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModoficar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMsjRut;
    private javax.swing.JTextField jTextApeMaterno;
    private javax.swing.JTextField jTextApePaterno;
    private javax.swing.JTextField jTextFieldDV;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextField jTextRut;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JComboBox<String> jcbCiudad;
    private javax.swing.JComboBox<String> jcbComuna;
    private javax.swing.JTextField jtfCalle;
    private javax.swing.JTextField jtfNumCalle;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
