package Vista.Clientes;

import Clases.Ciudad;
import Clases.Cliente;
import Clases.Comuna;
import Clases.Direccion;
import Operaciones.LlenarCombo;
import Operaciones.OperacionesClientes;
import Validacion.Validar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * @author rodrigo
 */
public class RegistrarClientes extends javax.swing.JPanel {

    LlenarCombo llenarCombo = new LlenarCombo();
    OperacionesClientes op = new OperacionesClientes();

    /**
     * Creates new form RegistrarClientes
     */
    public RegistrarClientes() throws SQLException {
        initComponents();
        Validar.validarCaracter(jTextFieldNombres, 20);
        Validar.validarCaracter(jTextApePaterno, 20);
        Validar.validarCaracter(jTextApeMaterno, 20);
        Validar.validarNumero(jTextTelefono, 9);
        Validar.validarRut(jTextRut, jTextFieldDV, jLabelMsjRut);
        Validar.validarCaracter(jtfCalle, 20);
        Validar.validarNumero(jtfNumCalle, 6);
        llenarCombo.llenarComboCiudad(jcbCiudad);
        llenarCombo.llenarComboComuna(jcbComuna, 0);
    }

    /**
     * Este metodo Reestablece todos os valores de JTextField y JComboBox
     */
    public void limpiarRegistroClientes() {

        jTextRut.setText("");
        jTextFieldDV.setText("");
        jTextFieldNombres.setText("");
        jTextApePaterno.setText("");
        jTextApeMaterno.setText("");
        jTextTelefono.setText("");
        jtfCalle.setText("");
        jtfNumCalle.setText("");
        jcbCiudad.setSelectedIndex(0);
        jcbComuna.setSelectedIndex(0);
        jLabelMsjRut.setText("");

    }

    /**
     * Metodo que permite habilita el boton registrar siempre y cuando los
     * campos contengan informacion y que los JCombo esten con una pcion valida
     */
    public void habilitarBotonRegistrar() {
        boolean estadoJLRut = jLabelMsjRut.isEnabled();
        String nombre = jTextFieldNombres.getText();
        String Paterno = jTextApePaterno.getText();
        String Materno = jTextApeMaterno.getText();
        String Calle = jtfCalle.getText();
        String Numero = jtfNumCalle.getText();

        int telefono = jTextTelefono.getText().length();
        if ((telefono != 9) || Calle.isEmpty() || Numero.isEmpty() || nombre.isEmpty() || Paterno.isEmpty() || Materno.isEmpty() || estadoJLRut || jcbCiudad.getSelectedIndex() == 0 || jcbComuna.getSelectedIndex() == 0) {
            jButtonRegistrar.setEnabled(false);
        } else {
            jButtonRegistrar.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabelMsjRut = new javax.swing.JLabel();
        jLabelMsjTel = new javax.swing.JLabel();
        jtfNumCalle = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcbComuna = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextRut = new javax.swing.JTextField();
        jTextFieldDV = new javax.swing.JTextField();
        jTextFieldNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbCiudad = new javax.swing.JComboBox<>();
        jtfCalle = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jTextApeMaterno = new javax.swing.JTextField();
        jTextApePaterno = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();
        jLabelGuion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 255, 0));
        kGradientPanel1.setkGradientFocus(800);
        kGradientPanel1.setkStartColor(new java.awt.Color(19, 62, 144));

        jLabelMsjRut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMsjRut.setForeground(new java.awt.Color(255, 51, 51));

        jLabelMsjTel.setForeground(new java.awt.Color(255, 51, 51));

        jtfNumCalle.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfNumCalleCaretUpdate(evt);
            }
        });

        jLabel11.setText("N° Calle");

        jLabel9.setText("Comuna:");

        jcbComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Comuna" }));
        jcbComuna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbComunaItemStateChanged(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unnamed.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Clientes");

        jTextRut.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextRutCaretUpdate(evt);
            }
        });

        jTextFieldDV.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldDVCaretUpdate(evt);
            }
        });
        jTextFieldDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDVActionPerformed(evt);
            }
        });

        jTextFieldNombres.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldNombresCaretUpdate(evt);
            }
        });

        jLabel2.setText("Rut:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("Apellido Paterno:");

        jLabel5.setText("Apellido Materno:");

        jLabel6.setText("Telefono:");

        jLabel10.setText("Calle");

        jLabel8.setText("Ciudad:");

        jcbCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCiudadItemStateChanged(evt);
            }
        });

        jtfCalle.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfCalleCaretUpdate(evt);
            }
        });

        jTextTelefono.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextTelefonoCaretUpdate(evt);
            }
        });

        jTextApeMaterno.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextApeMaternoCaretUpdate(evt);
            }
        });

        jTextApePaterno.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextApePaternoCaretUpdate(evt);
            }
        });

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setEnabled(false);
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jLabelGuion.setText("-");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRegistrar)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextApeMaterno, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextApePaterno)
                                    .addComponent(jTextFieldNombres)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextRut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelGuion, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelMsjTel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfNumCalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelMsjRut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel7)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMsjRut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelGuion)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabelMsjTel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNumCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(27, 27, 27)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed

        Cliente cliente = new Cliente();
        Direccion dire = new Direccion();

        boolean estado;

        //Recuperamos los datos y los asignamos a los Objetos Cliente y Direccion
        cliente.setRut(jTextRut.getText());
        cliente.setDv(jTextFieldDV.getText());
        cliente.setNombre(jTextFieldNombres.getText());
        cliente.setApePaterno(jTextApePaterno.getText());
        cliente.setApeMaterno(jTextApeMaterno.getText());
        cliente.setTelefono(jTextTelefono.getText());

        dire.setNombreCalle(jtfCalle.getText());
        dire.setNumeroCalle(jtfNumCalle.getText());

        //Recuperamos el objeto dentro del Jcombo seleccionado y procedemos a sacar su Id
        Comuna comuna = (Comuna) jcbComuna.getSelectedItem();
        int idCom = comuna.getIdComuna();
        dire.setIdComuna(String.valueOf(idCom));

        estado = op.ingresarCliente(cliente, dire);

        if (estado) {
            JOptionPane.showMessageDialog(null, "Cliente ingresado correctamente");
            limpiarRegistroClientes();
        } else {
            JOptionPane.showMessageDialog(null, "Ups Algo Salio mal y no se pudo registrar el cliente");
        }


    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jTextRutCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextRutCaretUpdate
        Validar.validarRut(jTextRut, jTextFieldDV, jLabelMsjRut);
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jTextRutCaretUpdate

    private void jTextFieldNombresCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldNombresCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jTextFieldNombresCaretUpdate

    private void jTextApePaternoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextApePaternoCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jTextApePaternoCaretUpdate

    private void jTextTelefonoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextTelefonoCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jTextTelefonoCaretUpdate

    private void jTextFieldDVCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldDVCaretUpdate
        Validar.validarRut(jTextRut, jTextFieldDV, jLabelMsjRut);
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jTextFieldDVCaretUpdate

    private void jTextFieldDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDVActionPerformed

        habilitarBotonRegistrar();
    }//GEN-LAST:event_jTextFieldDVActionPerformed

    private void jTextApeMaternoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextApeMaternoCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jTextApeMaternoCaretUpdate

    private void jtfCalleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfCalleCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jtfCalleCaretUpdate

    private void jtfNumCalleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfNumCalleCaretUpdate
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jtfNumCalleCaretUpdate

    private void jcbCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCiudadItemStateChanged
        habilitarBotonRegistrar();
        Ciudad ciudad = (Ciudad) this.jcbCiudad.getSelectedItem();//recuperamos el objeto (Ciudad) que esta en jComboBox, segun el Item Seleccionda
        int idCiu = ciudad.getIdCiudad();//Recuperamos el Id del Objeto Ciudad 
        try {
            llenarCombo.llenarComboComuna(jcbComuna, idCiu);//enviamos el JComboBoxComuna y el Id de la de la Ciudad 
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jcbCiudadItemStateChanged

    private void jcbComunaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbComunaItemStateChanged
        habilitarBotonRegistrar();
    }//GEN-LAST:event_jcbComunaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGuion;
    private javax.swing.JLabel jLabelMsjRut;
    private javax.swing.JLabel jLabelMsjTel;
    private javax.swing.JTextField jTextApeMaterno;
    private javax.swing.JTextField jTextApePaterno;
    private javax.swing.JTextField jTextFieldDV;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextField jTextRut;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JComboBox<String> jcbCiudad;
    private javax.swing.JComboBox<String> jcbComuna;
    private javax.swing.JTextField jtfCalle;
    private javax.swing.JTextField jtfNumCalle;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
